name: Document

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install depend
        run: |
          pip install pdoc3
          pip install .
